"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 3.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import datetime
import mimetypes
import environ
from django.conf import settings
from pathlib     import Path
from django.http import HttpResponse
env = environ.Env()
environ.Env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = env('SECRET_KEY')

# SECRET_KEY = os.environ.get('SECRET_KEY','=-=' )
# LINUX:   export SECRET_KEY="=-="
# Windows: set SECRET_KEY="=-="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
## ON SERVER========================
# In passenger_wsgi.py : there is only one line 
# from application.wsgi import application

## SSL==================================
SECURE_SSL_REDIRECT = False  # True if HTTPS
SECURE_HSTS_PRELOAD = False  # True if HTTPS
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SESSION_COOKIE_SECURE = True
## Secure==================================
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
##==================================
ALLOWED_HOSTS = ['*']
CORS_ALLOW_ALL_ORIGINS = True

SESSION_EXPIRE_SECONDS = 4 * 60 * 60  # Default unit : Seconds # 4hours
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = '/'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000

AUTH_USER_MODEL= 'Myapp.UserApp'

# Application definition
INSTALLED_APPS = [
    # My Libraries
    'csp',
    'Myapp',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'jazzmin',
    'import_export',
    # 'rangefilter',
    'admin_honeypot',
    # "debug_toolbar",
    # Built-in
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
]

## On Server to hide DRF : 
# REST_FRAMEWORK = {
#     'DEFAULT_RENDERER_CLASSES': (
#         'rest_framework.renderers.JSONRenderer',
#     ),
#     'NON_FIELD_ERRORS_KEY': 'error',
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     )
# }
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=3),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=30),
    'USER_ID_FIELD': 'username',
    'USER_ID_CLAIM': 'username',
}

JAZZMIN_SETTINGS = {
    "site_brand": "Panneau d'administration",
    "order_with_respect_to": ["Myapp.DOT", "Myapp.actel", "Myapp.Doleance", "Myapp.UserAPP","Myapp.LogUser"],
    "show_ui_builder": False,
    "welcome_sign": "Welcome to administration panel",
    "copyright": "Unité Recherche & Développement",
    "custom_css": None,
    "custom_js": None,
    "related_modal_active": True,
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "hide_models": [],
    "hide_apps": ["auth"],
     "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        # {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        # external url that opens in a new window (Permissions can be added)
        # {"name": "Support", "url": "/URL/", "new_window": True},
        # model admin to link to (Permissions checked against model)
        {"model": "auth.Group"},
        
        # App with dropdown menu to all its models pages (Permissions checked against models)
        # {"app": "Myapp"},
    ],
}
JAZZMIN_UI_TWEAKS = {
    "theme": "journal", #
    "dark_mode_theme": None,
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-blue",
    "sidebar": "sidebar-dark-info",
    "navbar": "navbar-dark  navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    
    "actions_sticky_top": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-success"
    },
}

IMPORT_EXPORT_IMPORT_PERMISSION_CODE = 'add'
IMPORT_EXPORT_EXPORT_PERMISSION_CODE = 'view'

MIDDLEWARE = [
    # "debug_toolbar.middleware.DebugToolbarMiddleware",
    'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.cache.UpdateCacheMiddleware',     # CACHE
    'Myapp.middlewares.RemoveServerHeaderMiddleware',
    'Myapp.middlewares.XContentTypeOptionsMiddleware',     # Override for other types
    'django.middleware.common.CommonMiddleware',
    
    # 'django.middleware.cache.FetchFromCacheMiddleware',  # CACHE
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    # 'Myapp.views.Log500ErrorsMiddleware'
    
]


# CSP_NONCE_IN_SCRIPT = True
CSP_INCLUDE_NONCE_IN = ['script-src','style-src','child-src','object-src']
# CSP_INCLUDE_NONCE_IN = ['script-src',]
CSP_DEFAULT_SRC = ("'self'")
# CSP_SCRIPT_SRC = ("'self'", "https://cdn.jsdelivr.net/npm/","'unsafe-inline'")
CSP_SCRIPT_SRC= ("'self'", "'unsafe-inline'" )
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'" )
# CSP_STYLE_SRC = ("'self'", "'unsafe-inline'"  , "https://fonts.googleapis.com")
CSP_IMG_SRC   = ("'self'", "https://medchalouli.com")
CSP_FONT_SRC  = ("'self'", "https://fonts.gstatic.com/")


# CACHE_MIDDLEWARE_ALIAS = 'default'  # which cache alias to use
# CACHE_MIDDLEWARE_SECONDS = 6    # 600 number of seconds to cache a page for (TTL)

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]
ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ "template" ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'
SWAGGER_SETTINGS = {
    'LOGIN_URL': '/administrator/',  # URL for the login button
    'LOGOUT_URL': '/administrator/logout/',  #getattr(settings, 'LOGOUT_URL', None),  # URL for the logout button
}

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },  
    
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':     env('DB_NAME'),     
        'USER':     env('DB_USER'),     
        'PASSWORD': env('DB_PASSWORD'), 
        'HOST':     env('DB_HOST'),     
        'PORT':     env('DB_PORT'),     
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
   {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'fr'
TIME_ZONE = 'Africa/Algiers'
USE_I18N = True
USE_L10N = True
USE_TZ = False

mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/javascript", ".js", True)

APPEND_SLASH = True
STATICFILES_DIRS = [BASE_DIR / 'assets/']

STATIC_ROOT = BASE_DIR / 'template' / 'assets'
MEDIA_ROOT = BASE_DIR / 'template' / 'media'

STATIC_URL = '/assets/'
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'