# Generated by Django 3.2.15 on 2023-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_doleance_actel'),
    ]

    operations = [
        migrations.AddField(
            model_name='actel',
            name='keyid',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
