# Generated by Django 3.2.15 on 2023-01-24 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20230115_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('keyid', models.CharField(default='-', max_length=200)),
            ],
            options={
                'verbose_name': 'Centre',
                'verbose_name_plural': "Centres d'OR",
                'db_table': 'centre',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='userapp',
            name='user',
            field=models.SmallIntegerField(choices=[(0, 'Administrateur'), (1, 'Gestionnaire ACTEL'), (2, 'Gestionnaire DOT'), (3, 'Gestionnaire DG')], default=0),
        ),
        migrations.AlterField(
            model_name='doleance',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'En cours de traitement'), (1, 'Traité')], default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrateur'), ('Actel', 'Gestionnaire ACTEL'), ('DOT', 'Gestionnaire DOT'), ('DG', 'Gestionnaire DG')], default='Administrateur', max_length=25),
        ),
        migrations.CreateModel(
            name='Regdor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.ImageField(blank=True, null=True, upload_to='regdorpic/')),
                ('dateReview', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commantaire')),
                ('centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Myapp.centre')),
            ],
            options={
                'verbose_name': 'appreciation',
                'verbose_name_plural': "Registre d'Or",
                'db_table': 'regdor',
                'managed': True,
            },
        ),
    ]
