# Generated by Django 3.2.15 on 2023-01-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_auto_20230124_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='user',
        ),
        migrations.AlterField(
            model_name='userapp',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Administrateur'), (1, 'Gestionnaire ACTEL'), (2, 'Gestionnaire DOT'), (3, 'Gestionnaire DG')], default=0),
        ),
    ]
