# Generated by Django 3.2.15 on 2023-01-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_auto_20230124_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regdor',
            name='comment',
        ),
    ]
