# Generated by Django 3.2.15 on 2023-01-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_remove_regdor_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
