# Generated by Django 3.2.15 on 2023-02-05 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_centre_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdor',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='actel',
            name='keyid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='doleance',
            name='satisfy',
            field=models.SmallIntegerField(choices=[(0, 'Négative'), (1, 'Neutre'), (2, 'Positive')], default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Satisfaction'),
        ),
        migrations.AlterField(
            model_name='doleance',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'En cours de traitement'), (1, 'Traitée')], default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
