# Generated by Django 3.2.15 on 2023-02-24 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_regdor_userat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centre',
            options={'managed': True, 'verbose_name': 'Structure', 'verbose_name_plural': "Structures d'OR"},
        ),
        migrations.AlterField(
            model_name='doleance',
            name='regType',
            field=models.SmallIntegerField(choices=[(0, 'Appréciation positive'), (1, 'Suggestions /Remareques'), (2, 'Doléances')], default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Administrateur'), (1, 'Gestionnaire ACTEL'), (2, 'Gestionnaire DOT'), (3, 'Gestionnaire DG'), (4, 'Gestionnaire OR')], default=0),
        ),
    ]
